services:
  front:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:-http://host.docker.internal:8080/api/v1}
    image: pet-marketplace-front:local
    container_name: petmarketplace-front
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped